title: Christopher Baim
logo: <img src="/assets/Profile.png" height="250">
description:
  MSc in Neuroscience
  <br><br>
  <b><a href="https://christopherbaim.github.io/">About</a></b><br>
  <b><a href="https://christopherbaim.github.io/pages/Portfolio">Developer Portfolio</a></b><br>
  <b><a href="https://christopherbaim.github.io/pages/Research">Research</a></b><br>
  <b><a href="https://christopherbaim.github.io/assets/ChrisBaimCV.pdf">CV</a></b><br>
  <br><br>
  <a href="https://www.linkedin.com/in/chrisbaim/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
icon: flavicon.ico