title: Christopher Baim
logo: "/assets/CB.png?raw=true"
description:
  MSc in Neuroscience
  <br><br>
  <b><a href="https://www.linkedin.com/in/chrisbaim/">Developer Portfolio</a></b>
  <b><a href="https://www.linkedin.com/in/chrisbaim/">Research</a></b>
  <a href="https://www.linkedin.com/in/chrisbaim/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
icon: flavicon.ico